# Config file for automatic testing at travis-ci.org
dist: xenial
language: python
cache: pip
python:
  - "3.7"

# Command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install:
  - pip install -U tox-travis codecov

# Command to run tests, e.g. python setup.py test
script:
  - tox


